### PR TITLE
Use -no-🥧 to avoid PIE warnings for Standard ML

### LINKED ISSUE #23: Annoying warnings from polyc compiler when running tests
It does not look pretty.
**TODO**: Figure out how we could mitigate it.
```
-- Day 1: Report Repair ---
cat input.txt | python3  day01.py         533ms      ✅
cat input.txt | rustc    day01.rs         753ms      ✅
/usr/bin/ld: /tmp/polyobj.413.o: warning: relocation in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
cat input.txt | polyc    day01.sml        419ms      ✅
cat input.txt | ruby     day01.rb         1231ms     ✅
cat input.txt | g++      day01.cpp        409ms      ✅
cat input.txt | python3  one-liner.py     280ms      ✅


--- Day 2: Password Philosophy ---
cat input.txt | gcc      day02.c          2ms        ✅
cat input.txt | g++      day02.cpp        3ms        ✅
/usr/bin/ld: /tmp/polyobj.532.o: warning: relocation in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
cat input.txt | polyc    day02.sml        404ms      ✅
cat input.txt | python3  day02.py         10ms       ✅


--- Day 3: Counting trees ---
cat input.txt | python3  day03.py         9ms        ✅
/usr/bin/ld: /tmp/polyobj.597.o: warning: relocation in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
cat input.txt | polyc    day03.sml        404ms      ✅
cat input.txt | python3  python_klyve.py  12ms       ✅
cat input.txt | gcc      day03.c          1ms        ✅

```

### PR DESCRIPTION
**Pull request by hypirion**
Properly resolves #23 instead of hacking around a warning.

You may want to flip the Docker commands around to save time, e.g. like

```Dockerfile
RUN apt-get update && apt-get install -yqq --no-install-recommends \
  build-essential git

RUN git clone https://github.com/polyml/polyml.git /tmp/polyml && cd /tmp/polyml && \
  CFLAGS=-no-pie ./configure --prefix=/usr && make && make compiler && make install && \
  cd / && rm -rf /tmp/polyml

RUN apt-get install -yqq --no-install-recommends \
  default-jdk \
# ...
```

But it kinda depends on how resistant you are to big images. It's also possible to use `--squash` and experimental mode... but I'm guessing most people won't have it enabled and thus it probably sets the bar to add ones own solution too high.

### CODE REVIEW

**Comment by Arxcis** [comment]
Yes I would like the images to be as small as possible, but I would also like to be pragmatic here. Since we are a polyglot project, it is expected to have to do custom stuff for different languages. 

I willl look more into this later tonight. Thank you for the proposal :+1:

**Comment by Arxcis** [comment]
A good/clean way to save on image size is to do the `polyml` specific stuff in a separate stage.

```Dockerfile
FROM alpine-with-git-and-make
....build polyml

FROM ubuntu:20.04
....copy polyml binaries and do the regular stuff
```

But I don't want to spend too much time on perfecting this. We have good download speeds in 2020, so I am not too concerned.

**Comment by hypirion** [comment]
@Arxcis: You'd have to use Ubuntu or any libc-based distro to build the base, but playing whack-a-mole trying to find all the files you need to move over is also kinda boring either way.

**Comment by Arxcis** [comment]
I am waiting to merge this, until #11 has been merged, as it also updates the `Dockerfile`, and will cause conflicts with this branch.

**Comment by hypirion** [comment]
Resolved the conflict and reordered commands around, to avoid waiting forever on build times the next time we want to add a new language.

**Comment by Arxcis** [comment]
Haha :+1: I just merged and made a layer for .sml in the Dockerfile. It was just 16MB extra . So all good :clap:

**Comment by Arxcis** [comment]
I will take a look at your latest c285fb5 to see if there is something I can improve on what I have locally right now :+1:

**Comment by Arxcis** [comment]
NEvermind. I am reverting my local conflict resolve, and pulingl your newest change instead. Testing...

**Comment by Arxcis** [comment]
image

Yes this was better, Now we can add layers at the bottom, without having to re-download the previous layers :+1:

Some splitting is good :+1: Initially I went too far in the no-splitting direction. I think we have hit a good middleground :+1:

**Pull request merged**
