### PR TITLE
Add deno language with example, and solutions for day 01 through 07

### PR DESCRIPTION
**Pull request by Arxcis**
https://deno.land/

### CODE REVIEW

**Comment by Arxcis** [comment]
Keeping this as a draft until #47 is resolved.

**Comment by Avokadoen** [comment]
Why would this be needed if we support nodejs?

**Comment by Arxcis** [comment]
@Avokadoen Hah! Outrageous. They are completely different languages. Instead of having a `main.js` file, you would have a `main.ts` file for example! :laughing:  (joking)

**Comment by Arxcis** [comment]
Instead of writing `no-de` you write  `de-no` !! The opposite :stuck_out_tongue_closed_eyes: 

The list goes on.... (no it doesn't)

**Comment by Arxcis** [comment]
Jokes aside. I really want to use this, instead of nodejs, that is why I am adding it. This also allows us to learn more about the minute differences between these two run-times, which I think is worth exploring :smile: as deno markets itself as a "better nodejs".

**Comment by Avokadoen** [comment]
It's worth noting that ts targets js, so you can run ts as long as you have node and the typescript transpiler. I think deno looks like an amazing project, so this definitely adds value to the repo!

**Pull request merged**
