### PR TITLE
Solved Day11 with deno.ts

### PR DESCRIPTION
**Pull request by Arxcis**
What am I doing wrong on part2?
I have looked at the code too much. Some fresh eyes would be appreciated :eyes: 

**Part 1 expected result:** 37, **actual** 37
**Part 2 expected result:** 26, **actual** 15
```sh
$ ../../lang/deno.sh solutions/day11.ts "io/*"
1,2d0
< 37
< 15
```

### CODE REVIEW

**Comment by hypirion** [comment]
I'll drag out an excerpt from the problem statement:

> The leftmost empty seat below would only see one empty seat, but cannot see any of the occupied ones:
> 
> ```
> .............
> .L.L.#.#.#.#.
> .............
> ```

What would your implementation return for the leftmost empty seat?

**Comment by Arxcis** [comment]
@hypirion Thank you for your question :pray: 

To answer it, I went ahead and isolated the raymarching-logic into a testable function. See: 2de91ad.

https://github.com/Arxcis/adventofcode2020/blob/2de91ad2cee3582d453d0a19a8c361fe71350944/days/day-11/solutions/raymarch.test.ts#L1-L23

**Test results:**
```sh
$ deno run solutions/raymarch.test.ts 
Check file:///home/jonas/git/github/Arxcis/adventofcode2020/days/day-11/solutions/raymarch.test.ts

Expect 1 to the east occupied. (@hypirion's test):
[ ".............", ".L.L.#.#.#.#.", "............." ]
[TEST PASS ✅] Expected NW to be 0 Actual: 0
[TEST PASS ✅] Expected N  to be 0 Actual: 0
[TEST PASS ✅] Expected NE to be 0 Actual: 0
[TEST PASS ✅] Expected W  to be 0 Actual: 0
[TEST PASS ✅] Expected E  to be 1 Actual: 1
[TEST PASS ✅] Expected SE to be 0 Actual: 0
[TEST PASS ✅] Expected S  to be 0 Actual: 0
[TEST PASS ✅] Expected SW to be 0 Actual: 0

Expect all adjecent occupied:
[ "###", "#L#", "###" ]
[TEST PASS ✅] Expected NW to be 1 Actual: 1
[TEST PASS ✅] Expected N  to be 1 Actual: 1
[TEST PASS ✅] Expected NE to be 1 Actual: 1
[TEST PASS ✅] Expected W  to be 1 Actual: 1
[TEST PASS ✅] Expected E  to be 1 Actual: 1
[TEST PASS ✅] Expected SE to be 1 Actual: 1
[TEST PASS ✅] Expected S  to be 1 Actual: 1
[TEST PASS ✅] Expected SW to be 1 Actual: 1

Expect none adjecent occupied:
[ "...", ".L.", "..." ]
[TEST PASS ✅] Expected NW to be 0 Actual: 0
[TEST PASS ✅] Expected N  to be 0 Actual: 0
[TEST PASS ✅] Expected NE to be 0 Actual: 0
[TEST PASS ✅] Expected W  to be 0 Actual: 0
[TEST PASS ✅] Expected E  to be 0 Actual: 0
[TEST PASS ✅] Expected SE to be 0 Actual: 0
[TEST PASS ✅] Expected S  to be 0 Actual: 0
[TEST PASS ✅] Expected SW to be 0 Actual: 0

Expect corner-case with 3 adjacent occupied:
[ "L#.", "##.", "..." ]
[TEST PASS ✅] Expected NW to be 0 Actual: 0
[TEST PASS ✅] Expected N  to be 0 Actual: 0
[TEST PASS ✅] Expected NE to be 0 Actual: 0
[TEST PASS ✅] Expected W  to be 0 Actual: 0
[TEST PASS ✅] Expected E  to be 1 Actual: 1
[TEST PASS ✅] Expected SE to be 1 Actual: 1
[TEST PASS ✅] Expected S  to be 1 Actual: 1
[TEST PASS ✅] Expected SW to be 0 Actual: 0

Expect opposite corner-case with 3 adjacent occupied:
[ "...", ".##", ".#L" ]
[TEST PASS ✅] Expected NW to be 1 Actual: 1
[TEST PASS ✅] Expected N  to be 1 Actual: 1
[TEST PASS ✅] Expected NE to be 0 Actual: 0
[TEST PASS ✅] Expected W  to be 1 Actual: 1
[TEST PASS ✅] Expected E  to be 0 Actual: 0
[TEST PASS ✅] Expected SE to be 0 Actual: 0
[TEST PASS ✅] Expected S  to be 0 Actual: 0
[TEST PASS ✅] Expected SW to be 0 Actual: 0
```

**Still 15 on part 2**
```sh
$ ../../lang/deno.sh solutions/day11.ts "io/*"
1,2d0
< 37
< 15
```

**Comment by Arxcis** [comment]
I ran my solution on @preng69 's io:
```sh
$ ../../lang/deno.sh solutions/day11.ts "io/*"
1,2d0
< 2275
< 133
```
**Expected**
https://github.com/Arxcis/adventofcode2020/blob/0d691ec9d9953e4acfddd7d8a383dc8484ecf0ca/days/day-11/io/preng.output#L1-L2

**Comment by Arxcis** [comment]
Aaaaaa, I think I get it now....
>The leftmost empty seat below would only see one empty seat, but cannot see any of the occupied ones:

:eyes:

**Pull request merged**
