### PR TITLE
Create LICENSE

### LINKED ISSUE #16: Which license should we have?
I have no idea. Github is suggesting to add a license everywhere. I am thinking the samller the better. MIT license perhaps. Does anyone have any feelings about this?

### PR DESCRIPTION
**Pull request by Arxcis**
Fixes #16

Is this OK with all contributors? @hypirion ? @preng69 ? @klyve ? @Stektpotet ? @tholok97 ? @Celebrian ? @Avokadoen ? @jorgenhanssen ?

MIT License is basically, anyone randomly stumbling upon this repo, can do whatever they want with the code. Any strong feelings about this?

### CODE REVIEW

**Comment by Stektpotet** [comment]
MIT sounds good to me, no opposing feelings towards using it!

**Comment by Celebrian** [comment]
Fine by me:D

**Comment by Arxcis** [comment]
Good :+1: If one more person agrees, we have a majority voting FOR MIT license - 5/9 - and I will be comfortable with merging.

**Comment by hypirion** [comment]
Legally speaking, you can't arbitrarily change license without the approval of _all_ contributors. That being said, I'd be surprised if anyone here would care.

It's fine by me.

**Comment by Arxcis** [comment]
@hypirion Aha, ok thank you for pointing that out :+1: I want to do it properly, since why not?  We have 5 Aye!, of 9. There is no rush. I am waiting for the last 4 ayes! :pray:

**Comment by tholok97** [comment]
Aye 👌

**Comment by Arxcis** [comment]
Hmm. I just discovered un-license https://unlicense.org/. It is a bit late to change anything now, but it was intereseting nonetheless to compare MIT license vs  https://unlicense.org/ :thinking:

**Comment by Arxcis** [comment]
Thank you for those who ayed 👍 I think I am going to close this PR, and mark it as a dead-end, as it has been difficult to get a voiced opinion from everyone. I realize it would have been easier if the LICENSE was bundled from the start. It is difficult to introduce this hindsight 🤔 I would like to make a new attempt with the unlisence later, but for now, I won't prioritize it.

**Pull request closed without merging**
