### PR TITLE
Renamed days/ -> 2020/

### PR DESCRIPTION
**Pull request by Arxcis**
## Why?
To get ready for `2021/`

## Demo
| Before | After this PR |
|----------|---------|
| image|image |

~Hmmm. CI is not running on this PR :thinking: ...... hmmmmmm.....~ NEVERMIND! Fixed in d7253cf, 1263127, 360e307

Sorry for big diff :eyes: 
image

### CODE REVIEW

**Review by Stektpotet — APPROVED** [review]
Maybe we can look into [reusing workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) (not that I have really dug any further into this thus far, so I don't know if they're of use here...) as an alternative for having a workflow for each of the days?

Otherwise, as far as I can see, everything seems in order 👍

**Comment by Stektpotet** [comment]
Also, do we want to have the current year inside a folder too, I'm guessing `day-00-example` is where it is simply because it's not tied to any year in specific?

**Comment by Arxcis** [comment]
> Maybe we can look into [reusing workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) (not that I have really dug any further into this thus far, so I don't know if they're of use here...) as an alternative for having a workflow for each of the days?

Oooo, cool. This is new information. Finally. We can create a reuseable base-workflow, to avoid duplicating code. 

We still need one workflow file per day, to get the status-badge per day, because status-badges are per workflow.

**Comment by Arxcis** [comment]
> Also, do we want to have the current year inside a folder too, I'm guessing `day-00-example` is where it is simply because it's not tied to any year in specific?

The example day is not part of any year. That is why I hoisted it up to root level. 

The plan was to add a 2021/-folder eventually, but not in this PR. This PR is just the prepwork, to support multiple years.

**Pull request merged**
