### PR TITLE
Day10: Updated README.md

### PR DESCRIPTION
**Pull request by Stektpotet**

### CODE REVIEW

**Comment by Stektpotet** [comment]
Checks fail because nothing is added to test.sh 🤔 

This is a side-effect of checks/actions/workflows being dispatched upon _any_ changes within the day's directory... Maybe that should be changed?

**Comment by Arxcis** [comment]
> Checks fail because nothing is added to test.sh thinking
> 
> This is a side-effect of checks/actions/workflows being dispatched upon _any_ changes within the day's directory... Maybe that should be changed?

I think we could ignore README updates, if that is what you are asking?
Add `paths: !README.md` to the workflows.

**Comment by Arxcis** [comment]
The test are still failing though, even if the workflow never runs, because this PR does not provide a valid solution for day 10. 

So it is not incorrect, to show a failing test on this PR, because this PR fails the test indeed :shrug: 

But a failing test on a README.md update, is not a blocker for merging :wink:

**Comment by Arxcis** [comment]
I will try to add this:
```
paths-ignore:
  README.md
```
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths


https://stackoverflow.com/a/62972393

**Pull request merged**
